obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TS)  += synaptics/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_TS)  += goodix/
obj-$(CONFIG_CYPRESS_TS)  += cypress/
obj-$(CONFIG_CYPRESS_TS)  += cyttsp5/
obj-$(CONFIG_WACOM_TS) += wacom/
obj-$(CONFIG_HIDEEP_TS)  += hideep/
