obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_PAD)  += synaptics/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_PAD)  += goodix/
obj-$(CONFIG_CYPRESS_PAD)  += cypress/
obj-$(CONFIG_CYPRESS_PAD)  += cyttsp5/
obj-$(CONFIG_WACOM_PAD) += wacom/
obj-$(CONFIG_HIDEEP_PAD)  += hideep/
